---
title: "about"
---

I am a multidisciplinary researcher with expertise in both wet lab and computational techniques, specialising in the processing and analysis of human clinical samples.

I was born in a small village in Bihar, India. My academic journey began during my bachelor's studies at Anugrah Narayan College, Patna, where I formed lasting friendships and developed a keen interest in science. Together with friends, I pursued a Master's degree in Animal Biotechnology at the University of Hyderabad. It was during this time, inspired by the cutting-edge genomics facility at the School of Life Sciences, that I developed a strong interest in genomics.

To further this interest, I joined the Laboratory of Molecular Oncology at the Centre for DNA Fingerprinting and Diagnostics (CDFD), Hyderabad, for my PhD. My doctoral research focused on early-onset sporadic rectal cancer (EOSRC), where I also developed a growing interest in organoid models and T cell–mediated immunopathogenesis. 

Following my research at CDFD, I moved to Queen Mary University of London, where I expanded my work by generating organoids from different regions of the mouse oral cavity and establishing organoid-T cell co-culture systems.

Currently at Barts Liver Centre, I am investigating the immunopathogenesis of early-stage Metabolic Dysfunction-Associated Steatohepatitis (MASH). My research focuses on profiling the T cell repertoire and its functional responses in early-stage MASH through single-cell sequencing approaches (CITE-seq and TCR-seq). I analyse immune cells derived from liver, blood, subcutaneous, and visceral adipose tissues of patients with mild to moderate MASH-associated fibrosis.

Beyond the lab, I am deeply committed to science communication and education, and I actively engage with students and broader communities to share knowledge and inspire curiosity in biomedical science.

