---
title: "activities"
---
::: {.justify-text}

Serving as a member of the Blizard Postdoctoral Committee at the Blizard Institute, representing fellow postdoctoral researchers in institute meetings and contributing to initiatives that support postdoc development and engagement.

<p style="text-indent: -22px; margin-left: 22px;">
STEM Ambassador at the Centre of the Cell, Queen Mary University of London. Engaged with school children through interactive sessions to foster curiosity in science and inspire future careers in STEM.
</p>

<p style="text-indent: -22px; margin-left: 22px;">
Gained training and research experience at the Centre for DNA Fingerprinting and Diagnostics (CDFD), India as part of the SARS-CoV-2 testing and sequencing initiative. Played a key role in establishing the RNA isolation facility and developed the standard operating procedure (SOP) for RNA extraction in alignment with guidelines from the World Health Organization (WHO) and the Indian Council of Medical Research (ICMR). Additionally, was responsible for training all initial volunteers involved in RNA isolation.
</p>
:::

> 